
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WildanZ
 */
public class BankHome extends javax.swing.JFrame {

    /**
     * Creates new form BankHome
     */
    public BankHome(String saldo) {
        initComponents();
        
        jTextField1.setText(saldo);
        int sld = Integer.parseInt(saldo);
        if (sld <= 50000) {
            JOptionPane.showMessageDialog(null, "Saldo minimal harus Rp 50000. Segera lakukan penyetoran untuk menghindari penutupan akun.", "Caution", 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ATM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 110, 22);

        jLabel2.setText("Saldo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 90, 60, 20);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 90, 130, 30);

        jButton1.setText("Tarik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 170, 90, 23);

        jButton2.setText("Setor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 170, 90, 23);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 200, 200, 23);

        setSize(new java.awt.Dimension(335, 314));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String trk = JOptionPane.showInputDialog(null,"Masukkan jumlah nominal","Penarikan Tunai",3);
        int tarik = 0;
        int saldo = 0;
        boolean huruf = false;
        float num1;
        
        try {
            num1 = Float.parseFloat(trk);
        } catch (NumberFormatException e) {
            huruf = true;
        }
        
        if (huruf) {
            JOptionPane.showMessageDialog(null, "Harap isi dengan benar", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            tarik = Integer.parseInt(trk);
            saldo = Integer.parseInt(jTextField1.getText());
        }
        
        if(tarik % 100 != 0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM tidak menerima uang koin\nSilakan ulangi lagi", "Transaksi Gagal", JOptionPane.ERROR_MESSAGE);
        } else if(tarik > saldo) {
            JOptionPane.showMessageDialog(null, "Saldo Anda tidak mencukupi\nSilakan lakukan penyetoran", "Transaksi Gagal", JOptionPane.ERROR_MESSAGE);
        } else if(tarik < 50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal pengambilan tunai adalah RP 50000", "Transaksi Gagal", JOptionPane.ERROR_MESSAGE);
        } else {
            int saldoBaru = saldo - tarik;
            String sBaru = Integer.toString(saldoBaru);
                
            this.dispose();
            new BankHome(sBaru).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String stor = JOptionPane.showInputDialog(null,"Masukkan jumlah nominal","Penyetoran Tunai",3);
        int setor = 0;
        int saldo = 0;
        boolean huruf = false;
        float num1;
        
        try {
            num1 = Float.parseFloat(stor);
        } catch (NumberFormatException e) {
            huruf = true;
        }
        
        if (huruf) {
            JOptionPane.showMessageDialog(null, "Harap isi dengan benar", "Alert", JOptionPane.ERROR_MESSAGE);
        } else {
            setor = Integer.parseInt(stor);
            saldo = Integer.parseInt(jTextField1.getText());
        }
        
        if(setor % 100 != 0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM tidak menerima uang koin\nSilakan ulangi lagi", "Transaksi Gagal", JOptionPane.ERROR_MESSAGE);
        } else if(setor < 50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai adalah RP 50000", "Transaksi Gagal", JOptionPane.ERROR_MESSAGE);
        } else {
            int saldoBaru = saldo + setor;
            String sBaru = Integer.toString(saldoBaru);
            
            this.dispose();
            new BankHome(sBaru).setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String saldo = "500000";
                new BankHome(saldo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
